version: '3.3'
services:

  teamspeak:
    build: ./ts3
    image: "craigtho/ts3:latest"
    container_name: "teamspeak-app"
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
      - 1222:22
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: database
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: Sp00kyP4SS!
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
    - type: volume
      source: ts-data
      target: /var/ts3server

  database:
    build: ./database
    image: "craigtho/mariadb-ts3:latest"
    container_name: "teamspeak-db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sp00kyP4SS!
      MYSQL_DATABASE: teamspeak
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql

volumes:
  ts-data:
  db-data:
